environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 4

cache:
  - "%LOCALAPPDATA%/Yarn"

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

test_script:
  - node --version
  - yarn --version
  - yarn test
