environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 4

cache:
  - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1
