name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, ubuntu-18.04, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: npm install
        run: npm ci

      - name: npm test
        run: npm test
